### ISSUE TITLE
Add HTTPS support

### ISSUE THREAD

**Issue by Wodric** [JohnMcLear/ep_mathjax#6]
Hi,

I'm using etherpad in https context with your plugin. It uses an unsecure URL to generate (or get ?) formula. In this context, we got a warning on browser and it brokes the security icon on URL.

The website used to generate (get?) the formula seems has https support.
It should be interresting to use HTTPS to avoid these warning.

Thanks for your feedback.

**Comment by JohnMcLear** [comment]
https://github.com/JohnMcLear/ep_mathjax/blob/master/static/js/hooks.js#L39 is the offending line

**Comment by JohnMcLear** [comment]
I changed to https://  that should fix it.
